import { expect, test } from '@playwright/test'
import path from 'node:path'

for (const theme of ['light', 'dark'] as const) {
  test(`Run details and Steps use the workbench dock in ${theme}`, async ({ page }) => {
    await page.emulateMedia({ colorScheme: theme })
    await page.goto(`/preview.html?run-dock&theme=${theme}`)
    const frame = page.locator('#run-dock-frame')
    await frame.getByRole('button', { name: 'Run 1', exact: true }).click()
    const main = frame.locator('[data-slot="workbench-main"]')
    const dock = frame.locator('[data-slot="dock-panel"][data-edge="left"]')
    await expect(dock).toBeVisible()
    await expect(main.locator('[data-slot="run-inspector"]')).toHaveCount(0)
    await expect(dock.getByRole('tab', { name: 'Run details', exact: true })).toHaveAttribute('aria-selected', 'true')
    const summary = dock.locator('[data-slot="run-inspector"]')
    await expect(summary).toContainText('Pull request #412')
    await expect(summary).toContainText('fix/checkout-502')
    await expect(summary).toContainText('1 failed, 1 passed')
    await expect(summary).toContainText('3 of 24 rounds')
    await expect(summary.locator('[data-slot="inspector-row-mark"]')).toHaveCount(2)
    const group = summary.locator('[data-slot="inspector-group"]').first()
    const prose = summary.locator('[data-slot="section-body"]').first()
    expect(Math.abs((await group.boundingBox())!.x + 12 - (await prose.boundingBox())!.x - 12)).toBeLessThan(1)
    expect(await summary.evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true)
    if (process.env.RUN_DOCK_FRAMES_DIR) await frame.screenshot({ path: path.join(process.env.RUN_DOCK_FRAMES_DIR, `details-after-${theme}.png`) })
    await summary.getByRole('button', { name: 'Flow file', exact: true }).click()
    await expect(page.getByRole('dialog')).toContainText('This is the file as it is now.')
    await page.keyboard.press('Escape')
    await frame.getByRole('radio', { name: 'Flow', exact: true }).click()
    await expect(dock.getByRole('tab', { name: 'Steps', exact: true })).toHaveAttribute('aria-selected', 'true')
    const steps = dock.locator('[data-slot="run-steps"]')
    await expect(steps).toContainText('Taken 4')
    await expect(steps).toContainText('Not reached 1')
    await expect(steps.locator('[data-selected]')).toContainText('Round 4')
    await steps.getByRole('button').filter({ hasText: 'Round 3' }).click()
    await expect(main.locator('[data-step="reviewer"]')).toHaveAttribute('data-selected', 'true')
    await steps.getByRole('button').filter({ hasText: 'Not reached' }).click()
    await expect(main.locator('[data-step="person"]')).toHaveAttribute('data-selected', 'true')
    expect(await steps.evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true)
    if (process.env.RUN_DOCK_FRAMES_DIR) await frame.screenshot({ path: path.join(process.env.RUN_DOCK_FRAMES_DIR, `steps-after-${theme}.png`) })
    await dock.getByRole('button', { name: 'Give this panel the whole area', exact: true }).click()
    await expect(main).toBeHidden()
    await expect(steps).toBeVisible()
    await dock.getByRole('button', { name: 'Back to the layout', exact: true }).click()
    await expect(main).toBeVisible()
    await frame.getByRole('button', { name: 'Hide the right panel', exact: true }).click()
    await expect(dock).toHaveCount(0)
    await frame.getByRole('button', { name: 'Show the right panel — 2 views', exact: true }).click()
    await expect(frame.locator('[data-slot="run-steps"]')).toBeVisible()
  })

  test(`an older Run omits unrecorded facts and the narrow window uses the same dock in ${theme}`, async ({ page }) => {
    await page.emulateMedia({ colorScheme: theme })
    await page.setViewportSize({ width: 680, height: 900 })
    await page.goto(`/preview.html?run-dock&older&theme=${theme}`)
    const frame = page.locator('#run-dock-frame')
    await frame.getByRole('button', { name: 'Run 1', exact: true }).click()
    await expect(frame.locator('[data-slot="dock-panel"][data-edge="left"]')).toHaveCount(0)
    await frame.getByRole('button', { name: 'Show the right panel — 2 views', exact: true }).click()
    const inspector = frame.locator('[data-slot="run-inspector"]:visible')
    await expect(inspector.locator('[data-slot="run-recording-gaps"]')).toContainText('base, budget, Seat details, Seat costs')
    await expect(inspector).not.toContainText('Not recorded')
    expect(await inspector.evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true)
    if (process.env.RUN_DOCK_FRAMES_DIR) await frame.screenshot({ path: path.join(process.env.RUN_DOCK_FRAMES_DIR, `older-narrow-after-${theme}.png`) })
    await frame.getByRole('button', { name: 'Hide this panel', exact: true }).click()
    await expect(frame.locator('[data-slot="workbench-main"]')).toBeVisible()
  })
}
