import { expect, test } from '@playwright/test'

for (const theme of ['light', 'dark'] as const) {
  test(`project / Team / Seat hierarchy and row states — ${theme}`, async ({ page }) => {
    await page.emulateMedia({ colorScheme: theme })
    await page.goto('/preview.html?sidebar-structure')
    await page.getByRole('combobox', { name: 'theme', exact: true }).selectOption(theme)
    const fixture = page.locator('#sidebar-structure')
    const tree = fixture.locator('[data-region="session-tree"]')
    await expect(tree.locator('[data-project-root]')).toHaveCount(3)
    await expect(tree.locator('[data-tone="waiting"], [data-tone="working"]')).toHaveCount(0)
    await expect(tree.locator('[data-sidebar-band="pinned"]')).toContainText('Pinned plan')
    const team = tree.getByRole('button', { name: 'Room Ship checkout retry', exact: true })
    await expect(team).toContainText('Needs you')
    await expect(tree.getByRole('button', { name: 'Show the agents in Ship checkout retry' })).toHaveAttribute('aria-expanded', 'false')
    await expect(tree.locator('[data-nested="true"]')).toHaveCount(0)
    const project = team.locator('xpath=ancestor::*[@data-project-root]')
    const projectHead = project.locator('[data-draggable]')
    const position = (row: typeof team) => row.locator('[data-slot="sidebar-menu-icon"]').evaluate(node => node.getBoundingClientRect().x)
    expect(await position(team)).toBeGreaterThan(await projectHead.locator('[data-slot="text"]').first().evaluate(node => node.getBoundingClientRect().x))

    await team.focus()
    await page.keyboard.press('ArrowRight')
    const seats = team.locator('xpath=ancestor::li').locator('[data-nested="true"] [data-region="session-row"]')
    await expect(seats).toHaveCount(3)
    const writer = seats.first().locator('[data-slot="sidebar-menu-button"]')
    await expect(writer).toBeFocused()
    expect(await position(writer)).toBeGreaterThan(await position(team))
    await expect(seats.nth(1).locator('[data-slot="sidebar-menu-state"]')).toHaveAttribute('aria-label', 'Needs you')
    const busy = project.locator('[data-region="session-row"]').filter({ hasText: 'Check build' })
    await expect(busy.locator('[data-slot="spinner"]')).toBeVisible()

    for (const width of [320, 200]) {
      await fixture.evaluate((node, size) => { (node as HTMLElement).style.width = `${size}px` }, width)
      await page.locator('body').click({ position: { x: 1000, y: 1 } })
      const state = team.locator('[data-sidebar-menu-state-full]')
      await expect(state).toBeVisible()
      const box = await state.boundingBox()
      const row = await team.boundingBox()
      expect(box!.x + box!.width).toBeLessThanOrEqual(row!.x + row!.width)
      expect(await fixture.evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
    }
    await writer.focus()
    await page.keyboard.press('ArrowLeft')
    await expect(team).toBeFocused()
    await expect(seats).toHaveCount(0)
  })
}

for (const theme of ['light', 'dark'] as const) {
  test(`quiet headers and nested rows preserve the sidebar rails — ${theme}`, async ({ page }) => {
    await page.emulateMedia({ colorScheme: theme, reducedMotion: 'reduce' })
    await page.goto('/preview.html?sidebar-structure')
    await page.getByRole('combobox', { name: 'theme', exact: true }).selectOption(theme)
    const fixture = page.locator('#sidebar-structure')
    const tree = fixture.locator('[data-region="session-tree"]')
    const team = tree.getByRole('button', { name: 'Room Ship checkout retry', exact: true })
    await team.focus()
    await page.keyboard.press('ArrowRight')
    const project = tree.locator('[data-project-root="/work/atlas"]')
    const header = project.locator('[data-draggable]')
    const seat = project.locator('[data-nested="true"] [data-region="session-row"]').first()
    const pinned = tree.locator('[data-sidebar-band="pinned"]')
    const runningTeam = tree.getByRole('button', { name: 'Room Check release notes', exact: true }).locator('xpath=ancestor::li[@data-slot="sidebar-menu-item"][1]')
    await expect(runningTeam.locator(':scope > div > [data-slot="sidebar-menu-badge"] [data-slot="spinner"]')).toBeVisible()
    await expect(tree.getByRole('button', { name: 'Other projects', exact: false })).toHaveAttribute('aria-expanded', 'true')
    await expect(tree.locator('[data-project-root="/work/compass"] [data-draggable] [data-slot="sidebar-menu-icon"]')).toHaveCount(0)
    const right = async (item: ReturnType<typeof tree.locator>) => {
      const box = await item.boundingBox()
      expect(box).not.toBeNull()
      return box!.x + box!.width
    }
    const textStart = (item: ReturnType<typeof tree.locator>) => item.evaluate(node => {
      const range = document.createRange()
      range.selectNodeContents(node)
      return range.getBoundingClientRect().x
    })
    for (const width of [320, 200]) {
      await fixture.evaluate((node, size) => { (node as HTMLElement).style.width = `${size}px` }, width)
      await page.locator('body').click({ position: { x: 1000, y: 1 } })
      await page.mouse.move(1000, 0)
      // The section and the project header retain the top-level start inset.
      expect(Math.abs(await textStart(header.locator('[data-slot="text"]').first()) - await textStart(tree.getByRole('button', { name: 'Other projects', exact: false }).locator('[data-slot="sidebar-menu-label-content"]')))).toBeLessThanOrEqual(1)
      await expect(header.locator('[data-slot="sidebar-menu-icon"]')).toHaveCount(0)
      const name = header.locator('[data-slot="text"]').first()
      await expect(name).toHaveCSS('font-size', '14px')
      await expect(name).toHaveCSS('font-weight', '400')
      const ink = await fixture.evaluate(node => ({ secondary: getComputedStyle(node).getPropertyValue('--hd-secondary-foreground').trim(), muted: getComputedStyle(node).getPropertyValue('--hd-muted-foreground').trim() }))
      await expect(name).toHaveCSS('color', ink.secondary)
      await expect(pinned.locator('[data-slot="group-label"]')).toHaveCSS('color', ink.muted)
      const chevron = header.locator('[data-slot="disclosure-chevron"]')
      await expect(chevron).toHaveCSS('opacity', '0')
      await header.hover()
      await expect(chevron).toHaveCSS('opacity', '1')
      await expect(project.getByRole('button', { name: 'New session in atlas', exact: true })).toHaveCSS('opacity', '1')
      const headerAction = project.getByRole('button', { name: 'Actions for atlas', exact: true })
      await expect(headerAction).toHaveCSS('opacity', '1')
      const topRail = await right(headerAction)
      await seat.locator('[data-slot="sidebar-menu-button"]').hover()
      const seatAction = seat.locator('[data-slot="sidebar-menu-action"]')
      await expect(seatAction).toHaveCSS('opacity', '1')
      expect(Math.abs(await right(seatAction) - topRail)).toBeLessThanOrEqual(1)
      await page.mouse.move(1000, 0)
      const spinner = seat.locator('[data-slot="spinner"]')
      await expect(spinner).toBeVisible()
      await expect(spinner).toHaveCSS('animation-name', 'none')
      // The mark occupies the same target column as the top-level action.
      expect(Math.abs(await right(spinner.locator('..')) - topRail)).toBeLessThanOrEqual(1)
      const leading = (item: ReturnType<typeof tree.locator>) => item.locator('[data-slot="sidebar-menu-icon"]').first().evaluate(node => node.getBoundingClientRect().x)
      const step = await fixture.evaluate(node => Number.parseFloat(getComputedStyle(node).getPropertyValue('--hd-space-5')) + Number.parseFloat(getComputedStyle(node).getPropertyValue('--hd-space-2')) + 1)
      expect(await leading(seat) - await leading(team)).toBeCloseTo(step, 0)
      expect(await leading(pinned) - await textStart(pinned.locator('[data-slot="group-label"]'))).toBeCloseTo(step, 0)
    }
    await header.focus()
    await expect(header.locator('[data-slot="disclosure-chevron"]')).toHaveCSS('opacity', '1')
    await page.keyboard.press('Enter')
    await expect(header).toHaveAttribute('aria-expanded', 'false')
    await expect(project.locator('[data-virtual-project]')).toHaveCount(0)
    await header.click()
    await expect(header).toHaveAttribute('aria-expanded', 'true')
  })
}

for (const theme of ['light', 'dark'] as const) {
  test(`indentation preserves headings, separators and row highlights — ${theme}`, async ({ page }) => {
    await page.goto(`/preview.html?sidebar-structure&theme=${theme}`)
    await page.getByRole('combobox', { name: 'theme', exact: true }).selectOption(theme)
    const fixture = page.locator('#sidebar-structure')
    const project = fixture.locator('[data-project-root="/work/atlas"]')
    const team = project.getByRole('button', { name: 'Room Ship checkout retry', exact: true })
    await team.focus()
    await page.keyboard.press('ArrowRight')
    const pinned = fixture.locator('[data-sidebar-band="pinned"]')
    const loose = project.locator('[data-region="session-row"]').filter({ hasText: 'Release notes' }).locator('[data-slot="sidebar-menu-button"]')
    const seats = project.locator('[data-nested="true"]')
    const writer = seats.locator('[data-slot="sidebar-menu-button"]').first()
    const reviewer = seats.locator('[data-region="session-row"]').filter({ hasText: 'Reviewer' })
    for (const width of [320, 200]) {
      await fixture.evaluate((node, size) => { (node as HTMLElement).style.width = `${size}px` }, width)
      await page.evaluate(() => (document.activeElement as HTMLElement)?.blur())
      await page.mouse.move(1000, 0)
      const origin = (await fixture.boundingBox())!.x
      const bounds = async (node: typeof team) => { const b = (await node.boundingBox())!; return [b.x - origin, b.x + b.width - origin] }
      const textX = (node: typeof team) => node.evaluate(el => { const r = document.createRange(); r.selectNodeContents(el); return r.getBoundingClientRect().x })
      expect.soft(await textX(pinned.locator('[data-slot="group-label"]')) - origin).toBe(24)
      expect.soft(await bounds(pinned.locator('[data-slot="separator"]'))).toEqual([16, width - 16])
      expect.soft(await bounds(pinned.locator('[data-slot="sidebar-menu-button"]'))).toEqual([16, width - 16])
      expect.soft(await bounds(loose)).toEqual([8, width - 8])
      expect.soft(await bounds(team)).toEqual([8, width - 8])
      expect.soft(await bounds(writer)).toEqual([37, width - 8])
      await expect.soft(project.locator('[data-virtual-project]')).toHaveCSS('border-left-width', '0px')
      await expect.soft(pinned.locator('[data-slot="sidebar-group-content"]')).toHaveCSS('border-left-width', '0px')
      await expect.soft(seats).toHaveCSS('border-left-width', '1px')
      const full = reviewer.locator('[data-sidebar-menu-state-full]')
      if (width === 200) {
        await expect.soft(full).toBeHidden()
        await expect.soft(reviewer.locator('[data-sidebar-menu-state-compact]')).toBeVisible()
        const title = reviewer.locator('[data-slot="sidebar-menu-label-content"] > span > span').first()
        expect.soft(await title.evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
      } else await expect.soft(full).toBeVisible()
    }
  })
}
