import { expect, test, type Locator, type Page } from '@playwright/test'
import path from 'node:path'

const open = async (page: Page, theme: 'light' | 'dark', scene = 'running') => {
  await page.emulateMedia({ colorScheme: theme })
  await page.goto(`/preview.html?stop-run=${scene}&theme=${theme}`)
  await page.evaluate(() => document.fonts.ready)
  const frame = page.locator('#stop-run-frame')
  const publicText = await frame.evaluate(node => [node.textContent, ...[...node.querySelectorAll('*')].flatMap(element => [...element.attributes].map(attribute => attribute.value))].join('\n'))
  expect(publicText).not.toMatch(/\/Users\/|[\w.+-]+@(?!example\.com\b|acme\.dev\b|harnessdesk\.app\b)[\w.-]+/)
  return frame
}
const capture = async (frame: Locator, name: string) => {
  if (process.env.STOP_RUN_FRAMES_DIR) await frame.screenshot({ path: path.join(process.env.STOP_RUN_FRAMES_DIR, name) })
}
for (const theme of ['light', 'dark'] as const) {
  for (const scene of ['default', 'cleanup'] as const) test(`the ${scene} stop question preview renders on load in ${theme}`, async ({ page }) => {
    await page.emulateMedia({ colorScheme: theme })
    await page.goto(`/preview.html?stop-run-dialog=${scene}&theme=${theme}`)
    await page.evaluate(() => document.fonts.ready)
    const dialog = page.getByRole('alertdialog', { name: scene === 'cleanup' ? 'Finish stopping this Run?' : 'Stop this Run?', exact: true })
    await expect(dialog).toBeVisible()
    await expect(page.getByRole('alertdialog')).toHaveCount(1)
    await expect(dialog.locator('[data-stop-seat="alpha"]')).toContainText('stops now')
    await expect(dialog.locator('[data-stop-seat="beta"]')).toContainText('stops when its current turn ends')
    await expect(dialog.getByRole('textbox', { name: 'Note' })).toHaveValue(scene === 'cleanup' ? 'The brief changed.' : '')
    if (scene === 'cleanup') await expect(dialog).toContainText('one Seat could not be released')
    const publicText = await dialog.evaluate(node => [node.textContent, ...[...node.querySelectorAll('*')].flatMap(element => [...element.attributes].map(attribute => attribute.value))].join('\n'))
    expect(publicText).not.toMatch(/\/Users\/|[\w.+-]+@(?!example\.com\b|acme\.dev\b|harnessdesk\.app\b)[\w.-]+/)
    await capture(dialog, `preview-${scene}-${theme}.png`)
    await dialog.getByRole('button', { name: scene === 'cleanup' ? 'Close' : 'Keep running', exact: true }).click()
    await expect(dialog).toBeHidden()
    const dial = page.getByLabel('Stop run question', { exact: true })
    await expect(dial).toHaveValue('off')
    await dial.selectOption(scene)
    await expect(dialog).toBeVisible()
    await dialog.getByRole('button', { name: scene === 'cleanup' ? 'Retry stop' : 'Stop run', exact: true }).click()
    await expect(dialog).toBeHidden()
  })

  test(`a resumed Run clocks live work and a second stop freezes at its own end in ${theme}`, async ({ page }) => {
    await page.clock.install()
    let frame = await open(page, theme, 'resumed')
    let card = frame.locator('[data-row="card-4-4"]')
    await expect(card).toContainText('Working')
    await expect(card).toContainText('so far')
    const live = await card.textContent()
    await page.clock.fastForward(60_000)
    await expect(card).not.toHaveText(live!)
    frame = await open(page, theme, 'restopped')
    card = frame.locator('[data-row="card-4-4"]')
    await expect(card).toContainText('Stopped')
    await expect(card).toContainText('7m')
    await expect(card).not.toContainText(/Working|so far/)
    await expect(frame.locator('[data-slot="run-current-step"]')).toContainText('Stopped')
    const frozen = await card.textContent()
    await page.clock.fastForward(60_000)
    await expect(card).toHaveText(frozen!)
    await frame.getByText('Stopped by you', { exact: true }).scrollIntoViewIfNeeded()
    await capture(frame, `restopped-${theme}.png`)
  })
  test(`the header and Overview stop one Run, with whole Seat lines and the stopped record in ${theme}`, async ({ page }) => {
    const frame = await open(page, theme)
    await capture(frame, `running-after-${theme}.png`)
    await frame.locator('[data-slot="run-header"]').getByRole('button', { name: 'Stop run…' }).click()
    const dialog = page.getByRole('alertdialog', { name: 'Stop this Run?' })
    await expect(dialog.locator('p').first()).toHaveText('The Run stops now and no further step starts.')
    await expect(dialog.locator('[data-stop-seat="alpha"]')).toContainText('stops now')
    await expect(dialog.locator('[data-stop-seat="beta"]')).toContainText('stops when its current turn ends')
    await expect(dialog.getByRole('button', { name: 'Stop run', exact: true })).toHaveAttribute('data-variant', 'default')
    await capture(dialog, `dialog-${theme}.png`)
    await dialog.getByRole('button', { name: 'Keep running' }).click()
    await frame.locator('[aria-label="Run"]').getByRole('button', { name: 'Stop run…' }).click()
    await dialog.getByRole('textbox', { name: 'Note' }).fill('The brief changed.')
    await dialog.getByRole('button', { name: 'Stop run', exact: true }).click()
    await expect(dialog).toBeHidden()
    await expect(frame).toContainText('Stopped by you')
    await expect(frame).toContainText('The brief changed.')
    await expect(frame.getByRole('button', { name: 'Stop run…' })).toHaveCount(0)
    const card = frame.locator('[data-row="card-4-4"]')
    await expect(card).toContainText('Stopped')
    await expect(card).not.toContainText(/Working|so far/)
    await expect(card.locator('[data-slot="chip"]')).toHaveCount(0)
    await expect(frame.locator('[data-slot="run-inspector"] [data-slot="inspector-tools"]')).toContainText('Stopped')
    await expect(frame.locator('[data-slot="run-current-step"]')).toContainText('Stopped')
    await frame.getByText('Stopped by you', { exact: true }).scrollIntoViewIfNeeded()
    await capture(frame.locator('[data-slot="run-workspace"]'), `stopped-${theme}.png`)
  })

  test(`a retained claimed card stops ticking while its Seat finishes, then rests in ${theme}`, async ({ page }) => {
    await page.clock.install()
    const frame = await open(page, theme, 'stopping')
    await expect(frame.locator('[data-finish-turn]')).toBeHidden()
    const card = frame.locator('[data-row="card-4-4"]')
    await expect(card).toContainText('Stopping')
    await expect(card).not.toContainText(/Working|so far/)
    await expect(frame.locator('[data-slot="run-inspector"] [data-slot="inspector-tools"]')).toContainText('Stopping')
    await expect(frame.locator('[data-slot="run-current-step"]')).toContainText('Stopping')
    const frozen = await card.textContent()
    await page.clock.fastForward(60_000)
    await expect(card).toHaveText(frozen!)
    await frame.getByText('Stopped by you', { exact: true }).scrollIntoViewIfNeeded()
    await capture(frame, `stopping-${theme}.png`)
    await frame.locator('[data-finish-turn]').evaluate((node: HTMLButtonElement) => node.click())
    await expect(card).toContainText('Stopped')
    await expect(card.locator('[data-slot="chip"]')).toHaveCount(0)
    await expect(frame.locator('[data-slot="run-inspector"] [data-slot="inspector-tools"]')).toContainText('Stopped')
    await expect(frame.locator('[data-slot="run-current-step"]')).toContainText('Stopped')
    await capture(frame, `stopped-retained-${theme}.png`)
  })

  test(`the abandon question transfers to Stop without abandoning, in ${theme}`, async ({ page }) => {
    const frame = await open(page, theme)
    await frame.getByRole('button', { name: 'Abandon card…' }).click()
    const abandon = page.getByRole('alertdialog', { name: 'Abandon card #4?' })
    await capture(abandon, `abandon-after-${theme}.png`)
    await abandon.getByRole('button', { name: 'Stop the run instead' }).click()
    await expect(abandon).toBeHidden()
    const dialog = page.getByRole('alertdialog', { name: 'Stop this Run?' })
    await expect(dialog).toBeVisible()
    await expect(page.getByRole('alertdialog')).toHaveCount(1)
    await dialog.getByRole('button', { name: 'Keep running' }).click()
    await expect(frame.getByRole('button', { name: 'Abandon card…' })).toBeVisible()
  })

  for (const width of [390, 760]) test(`the question and its actions fit at ${width}px in ${theme}`, async ({ page }) => {
    await page.setViewportSize({ width, height: 700 })
    const frame = await open(page, theme, 'narrow')
    await frame.locator('[data-slot="run-header"]').getByRole('button', { name: 'Stop run…' }).click()
    const dialog = page.getByRole('alertdialog', { name: 'Stop this Run?' })
    const box = (await dialog.boundingBox())!
    expect(box.x).toBeGreaterThanOrEqual(0)
    expect(box.x + box.width).toBeLessThanOrEqual(width)
    expect(await dialog.evaluate(node => node.scrollWidth <= node.clientWidth + 1)).toBe(true)
    for (const name of ['Stop run', 'Keep running']) await expect(dialog.getByRole('button', { name, exact: true })).toBeInViewport()
    expect(await dialog.locator('[data-stop-seat]').evaluateAll(rows => rows.every(row => {
      const text = row.querySelector('[data-slot="list-row-subtitle"]')!
      return getComputedStyle(text).textOverflow !== 'ellipsis' && text.scrollWidth <= text.clientWidth + 1
    }))).toBe(true)
    await capture(dialog, `dialog-${width}-${theme}.png`)
  })

  test(`empty, pending and failed stop questions remain usable in ${theme}`, async ({ page }) => {
    let frame = await open(page, theme, 'empty')
    await frame.locator('[data-slot="run-header"]').getByRole('button', { name: 'Stop run…' }).click()
    let dialog = page.getByRole('alertdialog')
    await expect(dialog).toContainText('No open Seats in this Run.')
    frame = await open(page, theme, 'pending')
    await frame.locator('[data-slot="run-header"]').getByRole('button', { name: 'Stop run…' }).click()
    dialog = page.getByRole('alertdialog')
    await dialog.getByRole('button', { name: 'Stop run', exact: true }).click()
    await expect(dialog.getByRole('button', { name: 'Stopping…' })).toBeDisabled()
    await capture(dialog, `pending-${theme}.png`)
    frame = await open(page, theme, 'failed')
    await frame.locator('[data-slot="run-header"]').getByRole('button', { name: 'Stop run…' }).click()
    dialog = page.getByRole('alertdialog')
    await dialog.getByRole('button', { name: 'Stop run', exact: true }).click()
    await expect(dialog).toContainText('one Seat could not be released')
    await expect(dialog.getByRole('button', { name: 'Retry stop', exact: true })).toBeEnabled()
    await expect(dialog.getByRole('button', { name: 'Close', exact: true })).toBeVisible()
    await capture(dialog, `failed-${theme}.png`)
    await dialog.getByRole('button', { name: 'Close', exact: true }).click()
    await expect(frame).toContainText('one Seat could not be released')
    await expect(frame.getByRole('button', { name: 'Stop run…' })).toHaveCount(0)
    await capture(frame, `cleanup-${theme}.png`)
    await frame.getByRole('button', { name: 'Retry stop…' }).click()
    await expect(dialog).toContainText('one Seat could not be released')
    await dialog.getByRole('button', { name: 'Retry stop', exact: true }).click()
    await expect(dialog).toBeHidden()
    await expect(frame.getByRole('button', { name: 'Retry stop…' })).toHaveCount(0)
  })

  test(`cleanup retry and its whole error fit at 390px in ${theme}`, async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 700 })
    const frame = await open(page, theme, 'cleanup')
    await frame.getByRole('button', { name: 'Retry stop…' }).scrollIntoViewIfNeeded()
    await expect(frame.getByRole('button', { name: 'Retry stop…' })).toBeInViewport()
    expect(await frame.evaluate(node => node.scrollWidth <= node.clientWidth + 1)).toBe(true)
    await capture(frame, `cleanup-390-${theme}.png`)
    await frame.getByRole('button', { name: 'Retry stop…' }).click()
    const dialog = page.getByRole('alertdialog', { name: 'Finish stopping this Run?' })
    await expect(dialog.getByRole('textbox', { name: 'Note' })).toHaveValue('The brief changed.')
    for (const name of ['Retry stop', 'Close']) await expect(dialog.getByRole('button', { name, exact: true })).toBeInViewport()
    await capture(dialog, `retry-390-${theme}.png`)
    await page.keyboard.press('Escape')
    await expect(dialog).toBeHidden()
    await expect(frame.getByRole('button', { name: 'Retry stop…' })).toBeVisible()
  })
}
