import { mkdir } from 'node:fs/promises'
import { join } from 'node:path'
import { expect, test } from '@playwright/test'

for (const theme of ['light', 'dark'] as const) test(`Storage page and confirmations in ${theme}`, async ({ page }, testInfo) => {
  const folder = process.env.STORAGE_FRAMES ?? testInfo.outputPath('storage')
  await mkdir(folder, { recursive: true })
  await page.emulateMedia({ colorScheme: theme })
  await page.setViewportSize({ width: 1200, height: 850 })
  await page.goto(`/preview.html?storage=page&theme=${theme}`)
  await page.evaluate(theme => { document.body.toggleAttribute('data-hd-dark-theme', theme === 'dark'); document.documentElement.style.colorScheme = theme }, theme)
  const frame = page.locator('[data-frame-id="storage-page"]')
  await expect(frame.getByText('148 MB', { exact: true })).toBeVisible()
  await page.evaluate(() => document.fonts.ready)
  await frame.screenshot({ path: join(folder, `page-${theme}.png`) })
  await expect(frame.getByText('Kept worktrees', { exact: true })).toBeVisible()
  await expect(frame.locator('[data-slot="row-desc"]')).toHaveCount(0)
  await frame.getByRole('button', { name: 'Review…', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Clean up inactive conversations' })
  await expect(dialog.getByRole('button', { name: 'Remove 2 worktrees', exact: true })).toBeVisible()
  await expect(dialog.getByText('.env', { exact: true })).toHaveCount(0)
  await frame.screenshot({ path: join(folder, `review-clean-${theme}.png`) })
  await dialog.getByRole('switch', { name: 'Also discard unsaved and ignored content' }).click()
  await expect(dialog.getByText('src/draft.ts', { exact: true })).toBeVisible()
  await expect(dialog.getByText('.env', { exact: true })).toBeVisible()
  await expect(dialog.getByRole('button', { name: 'Remove 3 worktrees', exact: true })).toHaveAttribute('data-variant', 'destructive')
  await frame.screenshot({ path: join(folder, `review-discard-${theme}.png`) })
  await dialog.locator('[data-slot="dialog-footer"]').getByRole('button', { name: 'Close', exact: true }).click()
  await frame.getByRole('button', { name: 'Discard worktree…', exact: true }).first().click()
  await expect(page.getByRole('alertdialog', { name: 'Discard worktree?' })).toBeVisible()
  await frame.screenshot({ path: join(folder, `kept-discard-${theme}.png`) })
  await page.getByRole('button', { name: 'Keep', exact: true }).click()
  await page.goto(`/preview.html?storage=measuring&theme=${theme}`)
  await page.evaluate(theme => { document.body.toggleAttribute('data-hd-dark-theme', theme === 'dark'); document.documentElement.style.colorScheme = theme }, theme)
  await expect(page.getByText('Measuring…', { exact: true })).toBeVisible()
  await page.locator('[data-frame-id="storage-measuring"]').screenshot({ path: join(folder, `measuring-${theme}.png`) })
})
