/**
 * Write the command-line reference out of the command table.
 *
 * `docs/cli.md` is for people driving their own work with `harnessdesk`: what
 * each command does, how to type it, what `--json` prints, how it ends and
 * what it is allowed to do. All of that is in the command table in
 * `packages/cli/src/cli.ts` already, beside the code that does it, because
 * that is where the person changing a command is looking. Restating it in a
 * Markdown file by hand would be a second source of truth, wrong within a
 * fortnight. So the Markdown is generated, and `--check` fails when it is
 * stale, which is how it stays honest without anybody remembering to update it
 * (the same idea as `docs/design-system.md` and `design-doc.mjs`).
 *
 * The table is read from the *built* command line, `packages/cli/dist`, so run
 * `pnpm build:node` first, or use `pnpm cli:doc`, which compiles the command
 * line and then writes the file. `pnpm verify` and CI build before they check.
 *
 *   node script/cli-doc.mjs            write docs/cli.md
 *   node script/cli-doc.mjs --check    fail if it is out of date
 *   node script/cli-doc.mjs --file F   write, or check, F instead of docs/cli.md
 *                                      (what the gate's own test uses)
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const OUT = path.join(root, 'docs/cli.md')

/** A table cell: the pipe is the one character that cannot be left in it. */
const cell = (text) => String(text).replaceAll('|', '\\|').replace(/\s*\n\s*/g, ' ')

/** What the first sentence of a description says, for the table at the top. */
export const firstSentence = (text) => {
  const hit = /^(.*?[.!?])(?:\s|$)/s.exec(String(text).trim())
  return hit ? hit[1] : String(text).trim()
}

/** The heading anchor GitHub gives a command's section. */
const anchor = (name) => `harnessdesk-${name.replaceAll(' ', '-')}`

/** `--flag VALUE` as it is typed. */
const spelled = (option) => (option.value === undefined ? option.flag : `${option.flag} ${option.value}`)

const TIERS = {
  read: 'read',
  run: 'run',
  answer: 'answer',
}

/**
 * The reference, as Markdown, from the command table and what its commands
 * share. Pure: it reads nothing, so a test can hand it a table of its own.
 */
export const render = ({ commands, exitCodes, globalOptions }) => {
  const lines = []
  const push = (...more) => lines.push(...more)

  push('# The `harnessdesk` command line')
  push('')
  push('*Generated by `script/cli-doc.mjs` from the command table in `packages/cli/src/cli.ts`. Do not edit — change the table and run `pnpm cli:doc`. This page is for people using the command line; `packages/cli/README.md` is for the people building it.*')
  push('')
  push('`harnessdesk` drives a running HarnessDesk from a terminal or a script: list its Teams and runs, start a flow, watch it, stop it, and answer the cards it addressed to you. It talks to the desk over a private socket on this Mac, so a desk has to be running. There is nothing to sign in to and no key to keep: the socket\'s file permissions are the only credential, and no command or flag takes one.')
  push('')

  push('## Install')
  push('')
  push('The command line ships inside the HarnessDesk app. To use it from a terminal, choose **HarnessDesk › Install command-line tool…** in the app\'s menu. That puts a small launcher called `harnessdesk` in a folder you own that is already on your `PATH`: `~/.local/bin`, or else `~/bin`. It never asks for an administrator\'s password and never edits a shell file. If neither folder is on your `PATH` it installs in `~/.local/bin` anyway, says where the file is, and gives you the one line that adds that folder to your `PATH`.')
  push('')
  push('The launcher runs the command line bundled in the app, on the app\'s own runtime, so you do not need Node. It finds the app again each time it runs, so updating or moving the app does not break it; if it cannot find the app it says so and exits 127. It never replaces a `harnessdesk` that HarnessDesk did not put there. Choose the menu item again, once it is installed, and it offers to remove the launcher. It is not offered on Windows yet.')
  push('')
  push('Working from a checkout of the repository, `node packages/cli/dist/src/bin.js` is the same program once `pnpm build:node` has run.')
  push('')

  push('## Picking a desk')
  push('')
  push('A desk is one running HarnessDesk, found by the folder it keeps its state in. `--home DIR` or `HARNESSDESK_HOME` picks it; with neither, it is `~/.harnessdesk`. If no desk is running there, the command exits 3 and names the desks it did find. It never connects to some other desk that happens to be up. `harnessdesk desks` lists the ones running.')
  push('')

  push('## Output')
  push('')
  push('- Output is text by default. `--json` prints JSON instead: one object for a command, and for a stream (`watch`, `waiting --watch`) one object per line. Errors always go to stderr.')
  push('- An error from the desk can run to several lines. Every line after the first starts with `  | `, so a line of a message from the desk, which an agent may have written, cannot pass for one the command line printed. A usage error is the command line\'s own, two lines: what was wrong, then the commands.')
  push('- Text that came from an agent or from a person, such as a Team\'s sentence, a card\'s title, a handoff or a note, is shown as data and never as instructions. In text output, control characters and terminal escape sequences are removed from it, so a handoff cannot rewrite your terminal, set your clipboard or forge a link. JSON output escapes them.')
  push('- Long text does not go on the command line. Give it as a file: `--brief-file PATH`, or `-` for standard input, or `--input NAME=@PATH`, or `--context-file PATH`.')
  const asking = commands.filter((command) => command.options.some((option) => option.flag === '--yes')).map((command) => `\`${command.name}\``)
  if (asking.length > 0) {
    push(`- ${asking.length === 1 ? 'The command that starts, stops or abandons work asks first' : 'The commands that start, stop or abandon work ask first'}: ${asking.length === 1 ? asking[0] : `${asking.slice(0, -1).join(', ')} and ${asking.at(-1)}`}. On a terminal ${asking.length === 1 ? 'it asks' : 'they ask'} a yes-or-no question; with no terminal ${asking.length === 1 ? 'it needs' : 'they need'} \`--yes\`, and without either ${asking.length === 1 ? 'it exits' : 'they exit'} 2.`)
  }
  push('')

  push('## What a command is allowed to do')
  push('')
  push('Each command needs one of three tiers, and the desk grants it or refuses it.')
  push('')
  push('- **read** reads, and subscribes to changes. It changes nothing. Granted by default.')
  push('- **run** spends, or takes work away: it opens a project, starts a flow, stops a run or abandons a card. Granted by default.')
  push('- **answer** speaks as you on a step a flow addressed to a person. **Off by default.** Turn it on with Settings › Permissions › Let command-line clients answer for me; a desk started by a script can set `HARNESSDESK_CLIENTS_MAY_ANSWER=1` in its environment instead. Without it, `card answer` exits 4 and prints `tierNotGranted`.')
  push('')
  push('Tiers are not a lock against code running as you. Starting a flow runs agents, and an agent runs commands, so `run` is close to running code as you, and anything that can open the desk\'s socket can use it. What the tiers do is keep the desk\'s human checks for a human: an answer to a person\'s card is accepted only where you allowed it, and shows on the Team\'s channel as given from the command line.')
  push('')
  push('The command line cannot answer a tool approval or a question (those are answered in the app), change seats, ceilings, agents, flows, triggers, accounts or settings, open a terminal, read files, or send into a conversation. And when it finds the markers the desk sets for its own seats (`HARNESSDESK_GOAL_ID` or `HARNESSDESK_LANE_ID`), it refuses every command above `read`: a seat uses its board tools, not the command line.')
  push('')

  push('## Flags every command takes')
  push('')
  for (const option of globalOptions) push(`- \`${spelled(option)}\`: ${option.description}`)
  push('')

  push('## Exit codes')
  push('')
  push('Every command ends with one of these. A command\'s own section lists the codes that mean something particular for it; any command can also end with 1, 2, 3, 4 or 6 as they are described here.')
  push('')
  push('| Code | Meaning |')
  push('| --- | --- |')
  for (const [code, meaning] of Object.entries(exitCodes)) push(`| ${code} | ${cell(meaning)} |`)
  push('')

  push('## Commands')
  push('')
  push('| Command | What it does | Tier |')
  push('| --- | --- | --- |')
  for (const command of commands) {
    push(`| [\`${command.name}\`](#${anchor(command.name)}) | ${cell(firstSentence(command.description))} | ${TIERS[command.tier] ?? command.tier} |`)
  }
  push('')

  for (const command of commands) {
    push(`### \`harnessdesk ${command.name}\``)
    push('')
    push('```')
    push(`harnessdesk ${command.usage}`)
    push('```')
    push('')
    push(command.description)
    push('')
    push(`Needs the **${TIERS[command.tier] ?? command.tier}** tier.`)
    push('')
    if (command.arguments.length > 0) {
      push('**Arguments**')
      push('')
      for (const argument of command.arguments) push(`- \`<${argument.name}>\`: ${argument.description}`)
      push('')
    }
    if (command.options.length > 0) {
      push('**Flags**')
      push('')
      for (const option of command.options) push(`- \`${spelled(option)}\`: ${option.description}`)
      push('')
    }
    push('**With `--json`**')
    push('')
    push(command.json)
    push('')
    push('**Exit codes**')
    push('')
    for (const [code, meaning] of Object.entries(command.exits)) push(`- \`${code}\`: ${meaning}`)
    push('')
  }

  push('## A first session')
  push('')
  push('```sh')
  push('# Is a desk running, and what is it doing?')
  push('harnessdesk status')
  push('')
  push('# See what a flow would do in a project, then start it. Nothing is spent until the start.')
  push('harnessdesk flow preview review-pr --project ~/code/app --input task="Fix the retry count"')
  push('harnessdesk flow start review-pr --project ~/code/app --input task="Fix the retry count"')
  push('')
  push('# From a script: no terminal to ask on, so say yes, and read the run and Team back as JSON.')
  push('harnessdesk flow start review-pr --project ~/code/app --input task="Fix the retry count" --yes --json')
  push('')
  push('# Wait for the run; its exit code says how it ended.')
  push('harnessdesk run wait RUN --timeout 3600; echo $?')
  push('')
  push('# See what is waiting for you, and answer a card that is.')
  push('harnessdesk waiting')
  push('harnessdesk card answer TEAM 4 merged')
  push('```')
  push('')

  return `${lines.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd()}\n`
}

/* Everything below is the command; above is importable. A test that had to
   run the generator to reach `render` would be a test of the filesystem and of
   a build. Both sides go through realpath, the guard `check-verify-steps.mjs`
   explains: `import.meta.url` is always resolved through symlinks and
   `process.argv[1]` is whatever was typed, so comparing them any other way
   turns the command into a silent exit 0 when the checkout is reached through
   a link — and a gate that does nothing and says nothing is the worst kind. */
const isMain =
  process.argv[1] != null && fs.realpathSync(process.argv[1]) === fs.realpathSync(fileURLToPath(import.meta.url))

if (isMain) {
  const fileFlag = process.argv.indexOf('--file')
  const out = fileFlag >= 0 ? path.resolve(process.argv[fileFlag + 1] ?? '') : OUT
  const shown = path.relative(root, out) || out

  const built = path.join(root, 'packages/cli/dist/src')
  if (!fs.existsSync(path.join(built, 'cli.js')) || !fs.existsSync(path.join(built, 'reference.js'))) {
    console.error('The command line is not built, so its command table cannot be read. Run: pnpm build:node')
    process.exit(1)
  }
  const { COMMANDS } = await import(pathToFileURL(path.join(built, 'cli.js')).href)
  const { EXIT_CODES, GLOBAL_OPTIONS } = await import(pathToFileURL(path.join(built, 'reference.js')).href)
  const text = render({ commands: COMMANDS, exitCodes: EXIT_CODES, globalOptions: GLOBAL_OPTIONS })

  if (process.argv.includes('--check')) {
    const existing = fs.existsSync(out) ? fs.readFileSync(out, 'utf8') : ''
    if (existing === text) {
      console.log(`${shown} is current.`)
      process.exit(0)
    }
    console.error(`${shown} is stale. Run: pnpm cli:doc`)
    process.exit(1)
  }

  fs.writeFileSync(out, text)
  console.log(`wrote ${shown} (${text.split('\n').length} lines)`)
}
