// Vendors the interface typeface into packages/ui/src/assets/fonts.
//
//   node script/vendor-fonts.mjs
//
// Geist (SIL OFL 1.1) is the interface face. It is checked in rather than
// fetched at build time: the app is an offline desktop app, and a font that
// arrives over the network is a font that sometimes does not arrive.
//
// Google serves Geist as one *variable* file per unicode range — the same
// woff2 answers 400, 500 and 600 — so each range is fetched once and declared
// with a weight range. Asking for three weights and writing three files is how
// you end up shipping the same 29KB three times.
//
// Only latin and latin-ext are kept. The stack's CJK fallbacks cover the rest,
// and Cyrillic nobody reads is still bytes in the bundle.
//
// Re-run after a Geist release, then commit the woff2 files and the
// regenerated fonts.css. The version Google is serving lands in VERSION.json.
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const out = join(root, 'packages/ui/src/assets/fonts')

/** 400 body, 500 titles, 600 the two names that earn it. */
const WEIGHTS = [400, 600]
const RANGES = ['latin', 'latin-ext']
/** Google serves woff2 only to a browser UA; a bare fetch gets truetype. */
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36'

const url = `https://fonts.googleapis.com/css2?family=Geist:wght@${WEIGHTS[0]}..${WEIGHTS[1]}&display=swap`
const css = await (await fetch(url, { headers: { 'User-Agent': UA } })).text()

mkdirSync(out, { recursive: true })

/** Each @font-face in Google's sheet is preceded by a comment naming its range. */
const faces = []
let version = 'unknown'

for (const block of css.split('/*').slice(1)) {
  const range = block.slice(0, block.indexOf('*/')).trim()
  if (!RANGES.includes(range)) continue
  const src = /src:\s*url\((https:[^)]+)\)/.exec(block)?.[1]
  const unicode = /unicode-range:\s*([^;]+);/.exec(block)?.[1].trim()
  if (!src || !unicode) throw new Error(`unparsable @font-face for ${range}`)
  version = /\/geist\/(v\d+)\//.exec(src)?.[1] ?? version

  const file = `geist-${range}.woff2`
  const bytes = Buffer.from(await (await fetch(src)).arrayBuffer())
  writeFileSync(join(out, file), bytes)
  faces.push({ file, unicode, bytes: bytes.length })
  process.stdout.write(`${file}  ${bytes.length} bytes\n`)
}

if (faces.length !== RANGES.length) {
  throw new Error(`expected ${RANGES.length} ranges, got ${faces.length}`)
}

const sheet = `/*
 * GENERATED by script/vendor-fonts.mjs — do not edit.
 *
 * Geist ${version}, one variable file per unicode range, SIL Open Font
 * License 1.1. See THIRD_PARTY_NOTICES.md and licenses/OFL-1.1-geist.txt.
 *
 * font-display: block, not swap. The interface is not an article: a flash of
 * the fallback would reflow every row in the app, and the file is local, so
 * the block never lasts long enough to see.
 */
${faces
  .map(
    (f) => `@font-face {
  font-family: 'Geist';
  font-style: normal;
  font-weight: ${WEIGHTS[0]} ${WEIGHTS[1]};
  font-display: block;
  src: url('./${f.file}') format('woff2');
  unicode-range: ${f.unicode};
}`,
  )
  .join('\n\n')}
`
writeFileSync(join(out, 'fonts.css'), sheet)
writeFileSync(
  join(out, 'VERSION.json'),
  `${JSON.stringify(
    { family: 'Geist', version, variable: true, weightRange: WEIGHTS, ranges: RANGES, license: 'OFL-1.1' },
    null,
    2,
  )}\n`,
)
process.stdout.write(`\nwrote fonts.css and VERSION.json (Geist ${version})\n`)
