/**
 * The test files that run in Node, not in jsdom.
 *
 * jsdom is built again for every file — the suite created it 475 times, and it
 * was 36% of the run's time. These files never use it: each passes with no DOM
 * at all, and nothing it imports asks whether there is one (`typeof window`,
 * `document?.`, a storage that may be missing). A module that did would take
 * its other branch here, and the test would stop proving what it was written
 * to prove. `src/node-environment.test.ts` holds both halves of that, so the
 * list can neither go stale nor drift into a silent change.
 *
 * To add a file, name it here. It then runs without the stand-ins in
 * `setup-tests.ts` as well, so a test that does need a DOM says so — `window
 * is not defined` — and belongs back in the default, which is jsdom. Every file
 * not named here keeps jsdom.
 */
export const NODE_TESTS: readonly string[] = [
  'src/components/Approvals.css.test.ts',
  'src/components/Composer.roles.test.ts',
  'src/components/Conversation.css.test.ts',
  'src/components/Markdown.lists.test.ts',
  'src/components/TeamRoomPane.css.test.ts',
  'src/components/WindowControls.css.test.ts',
  'src/components/conversation-layout-regressions.test.ts',
  'src/components/conversation-layout-roles.test.ts',
  'src/components/reading-column.test.ts',
  'src/design/faces.census.test.ts',
  'src/design/primitives/Banner.css.test.ts',
  'src/design/tokens.contrast.test.ts',
  'src/design/ui/composer.parity.test.ts',
  'src/lib/account-badge.test.ts',
  'src/lib/accounts.test.ts',
  'src/lib/acp-registry.test.ts',
  'src/lib/agents.test.ts',
  'src/lib/ansi.test.ts',
  'src/lib/avatars.test.ts',
  'src/lib/backup-words.test.ts',
  'src/lib/balance-series.test.ts',
  'src/lib/board-facts.test.ts',
  'src/lib/brands.test.ts',
  'src/lib/browser-load-error.test.ts',
  'src/lib/burn.test.ts',
  'src/lib/cache-health.test.ts',
  'src/lib/ceilings.test.ts',
  'src/lib/clock.test.ts',
  'src/lib/composer-slots.test.ts',
  'src/lib/context-envelope.test.ts',
  'src/lib/context-usage.test.ts',
  'src/lib/conversation-map.test.ts',
  'src/lib/diff.test.ts',
  'src/lib/editor.test.ts',
  'src/lib/evidence.test.ts',
  'src/lib/export-session.test.ts',
  'src/lib/flow-layout.test.ts',
  'src/lib/flow-model.test.ts',
  'src/lib/flow-overlay.test.ts',
  'src/lib/flows.test.ts',
  'src/lib/git-columns.test.ts',
  'src/lib/git-graph.test.ts',
  'src/lib/git-refs.test.ts',
  'src/lib/git-trouble.test.ts',
  'src/lib/git-view.test.ts',
  'src/lib/goal-run.test.ts',
  'src/lib/goals.test.ts',
  'src/lib/group-items.test.ts',
  'src/lib/handoff.test.ts',
  'src/lib/health.test.ts',
  'src/lib/images.test.ts',
  'src/lib/inbox.test.ts',
  'src/lib/insight.test.ts',
  'src/lib/installs.test.ts',
  'src/lib/intake.test.ts',
  'src/lib/ledger.test.ts',
  'src/lib/limits.test.ts',
  'src/lib/needs-you.test.ts',
  'src/lib/notice-policy.test.ts',
  'src/lib/options.test.ts',
  'src/lib/overview-strip.test.ts',
  'src/lib/paid.test.ts',
  'src/lib/paths.test.ts',
  'src/lib/plan-edits.test.ts',
  'src/lib/plan-strip.test.ts',
  'src/lib/plans-table.test.ts',
  'src/lib/plugins.test.ts',
  'src/lib/profile.test.ts',
  'src/lib/projects.test.ts',
  'src/lib/queue.test.ts',
  'src/lib/readiness.test.ts',
  'src/lib/review-publication.test.ts',
  'src/lib/run-reason.test.ts',
  'src/lib/search-highlight.test.ts',
  'src/lib/seat-names.test.ts',
  'src/lib/sessions.test.ts',
  'src/lib/shapes.test.ts',
  'src/lib/shortcuts.test.ts',
  'src/lib/side-by-side.test.ts',
  'src/lib/system-notifications.test.ts',
  'src/lib/tasks.test.ts',
  'src/lib/team-overview.test.ts',
  'src/lib/team-seats.test.ts',
  'src/lib/todos.test.ts',
  'src/lib/tool-names.test.ts',
  'src/lib/tool-result.test.ts',
  'src/lib/trace.test.ts',
  'src/lib/triggers.test.ts',
  'src/lib/turn-summary.test.ts',
  'src/lib/turn-view.test.ts',
  'src/lib/usage-alerts.test.ts',
  'src/lib/usage.test.ts',
  'src/lib/versions.test.ts',
  'src/panels/Workbench.css.test.ts',
  'src/panels/layers.test.ts',
  'src/panels/lights.test.ts',
  'src/state/layout.test.ts',
  'src/state/login.test.ts',
  'src/state/presets.test.ts',
  'src/state/workbench.test.ts',
  'src/styles/border-default.test.ts',
  'src/styles/editor-tokens.test.ts',
  'src/styles/editorial-tokens.test.ts',
  'src/styles/row-height-alias.test.ts',
  'src/styles/shadcn-themes.test.ts',
]
